version: '3.3'

services:

  lds-memory:
    image: lds-memory:dev
    ports:
    - "9090:9090"
    volumes:
    - ldsmemoryconf:/conf:ro
    - ldsmemoryschemas:/schemas:ro

volumes:
  ldsmemoryconf:
    driver: local
    driver_opts:
      type: none
      device: ${CONF_FOLDER}
      o: bind
  ldsmemoryschemas:
    driver: local
    driver_opts:
      type: none
      device: ${SCHEMA_FOLDER}
      o: bind
