version: '3.3'

services:

  lds:
    image: lds-memory:dev
    ports:
    - "9090:9090"
    volumes:
    - ldsmemoryconf:/conf:ro
    - ldsmemoryschemas:/schemas:ro

volumes:
  ldsmemoryconf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/conf
      o: bind
  ldsmemoryschemas:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/schemas
      o: bind
